### ISSUE TITLE
JSON array to String

### ISSUE THREAD

**Issue by radianttap** [utahiosmac/Marshal#79]
How can Marshal be extended to allow converting a JSON like this:

`"somekey": ["s1", "s2", "s3"]`

into this

`"s1,s2,s3"`

I had few multiple false starts already, can't figure it out.

**Comment by jarsen** [comment]
Do you have a specific reason for wanting to extend Marshal in this case?

Could you just do something like this?

``` swift
let strings: [String] = try json.value(for: "somekey")
let joinedString = strings.joined(separator: ",")
```

**Comment by radianttap** [comment]
Thanks! This will do as shortcut.

The reason I wanted to extend it is to automate generation of the `update()` calls for each entity in my data model:

```
    public func update(object: MarshaledObject, inContext context: NSManagedObjectContext) throws {

        if let key = NavigationNode.jsonKeys["childNodesCount"] { childNodesCount = try object.value(for: key) }
...
```

(jsonKeys maps from coredata attributes to whatever is coming from JSON).

I am using custom mogenerator templates for this and it would be pretty unwieldy pretty soon if I start adding this:

```
if let key = NavigationNode.jsonKeys["csvNavigationTypes"] {
    let strings: [String] = try object.value(for: key)
    csvNavigationTypes = strings.joined(separator: ",")
}
```

as exceptions. I can do post-generation changes like above, only need to remember doing them each time model classes are regenerated. Not a big issue for this particular model, but would like a cleaner solution.

I also auto-generate `marshaled()` methods so would need the opposite direction too.

**Comment by jarsen** [comment]
You might consider then writing reusable functions for transforming to CSV and back.

I think the difficulty here is how do you extend the behavior to provide this behavior for only a subset of `[String]`.

We have been discussing adding an optional transform function to the API in #73. This could help with this as well since you could do something like:

``` swift
let csv = try json.value(for: "somekey" transform: arrayToCSV)
```

where `csvTransformer` is some function that joins your `[String]` -> String

When marshaling, you'd still just write a `csvToArray` type function which you call on your csv value.

**Comment by radianttap** [comment]
Thanks, the transform approach sounds really good. I'll keep my eye on the #73 then
